version: '3'
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - APP_PORT=3000
      - JWT_SECRET=gatopreto
      # Os dados abaixo se referem ao container `db`
      # Dica: Relembre aqui da comunicação interna entre containers
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=database
      - DB_PORT=3306

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  database:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
